### ISSUE TITLE
Android8.0上 失效

### ISSUE THREAD

**Issue by rorschach** [Sunzxyong/Recovery#31]
> 07-25 21:06:58.478 18718-18718/? W/System.err: java.lang.IllegalAccessException: java.lang.Class<com.android.internal.os.RuntimeInit$UncaughtHandler> is not accessible from java.lang.Class<com.zxy.recovery.c.a>
07-25 21:06:58.479 18718-18718/? W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at com.zxy.recovery.c.a.a(MyApplication:26)
        at com.zxy.recovery.c.a.a(MyApplication:37)
        at com.zxy.recovery.core.c.uncaughtException(MyApplication:99)
        at com.tencent.bugly.crashreport.crash.f.b(MyApplication:354)
        at com.tencent.bugly.crashreport.crash.f.uncaughtException(MyApplication:372)
        at com.amap.api.a.a.iv.uncaughtException(Unknown Source)
        at com.amap.api.a.a.jm.uncaughtException(Unknown Source)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
07-25 21:06:58.651 19636-19636/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.plusmoney.managerplus:recover, PID: 19636
    java.lang.RuntimeException: Unable to start service com.zxy.recovery.core.RecoveryService@c36d447 with Intent { cmp=com.plusmoney.managerplus/com.zxy.recovery.core.RecoveryService (has extras) }: com.zxy.recovery.b.a: The context is not initialized
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3495)
        at android.app.ActivityThread.-wrap23(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by:

**Comment by rorschach** [comment]
我们的产品同时接入了Bugly，导致这个问题的原因是否为Recovery与Bugly冲突？

**Comment by Sunzxyong** [comment]
@rorschach 请更新到v1.0.0版本。
