### ISSUE TITLE
crash when click sure to restart and clear

### ISSUE THREAD

**Issue by soymantag** [Sunzxyong/Recovery#4]
FATAL EXCEPTION: main
                                                                     Process: com.zxy.recovery.test, PID: 8593
                                                                     java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.zxy.recovery.test.App
                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:587)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4792)
                                                                         at android.app.ActivityThread.access$1900(ActivityThread.java:158)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5564)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                      Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.zxy.recovery.test.App
                                                                         at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:219)
                                                                         at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:238)
                                                                         at android.app.Application.attach(Application.java:187)
                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:996)
                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:980)
                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:582)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4792) 
                                                                         at android.app.ActivityThread.access$1900(ActivityThread.java:158) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5564) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                      Caused by: java.lang.ClassNotFoundException: com.zxy.recovery.test.App
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.Class.forName(Class.java:308)
                                                                         at java.lang.Class.forName(Class.java:272)
                                                                         at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:207)
                                                                         at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:238) 
                                                                         at android.app.Application.attach(Application.java:187) 
                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:996) 
                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:980) 
                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:582) 
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4792) 
                                                                         at android.app.ActivityThread.access$1900(ActivityThread.java:158) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5564) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zxy.recovery.test.App" on path: DexPathList[[zip file "/data/app/com.zxy.recovery.test-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                         at java.lang.Class.classForName(Native Method) 
                                                                         at java.lang.Class.forName(Class.java:308) 
                                                                         at java.lang.Class.forName(Class.java:272) 
                                                                         at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:207) 
                                                                         at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:238) 
                                                                         at android.app.Application.attach(Application.java:187) 
                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:996) 
                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:980) 
                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:582) 
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4792) 
                                                                         at android.app.ActivityThread.access$1900(ActivityThread.java:158) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5564) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                     	Suppressed: java.lang.ClassNotFoundException: com.zxy.recovery.test.App
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         		... 20 more
                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by gq13834114692** [comment]
点清除缓存重启应用，再打开app就报错，同楼上

**Comment by Sunzxyong** [comment]
Please try to close instant run
